# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9lQ4qX1pC8Km2NCFLYPqutJ-s8-GKE-
"""

import matplotlib.pyplot as plt
from kits19.starter_code.utils import load_case
from pathlib import Path
import nibabel as nib
from imageio import imwrite
import os
from keras.preprocessing.image import ImageDataGenerator


def check_dir(path):
  if not path.exists():
    path.mkdir()



def preprocess_vol(path):
  seed = 1
  datagen = ImageDataGenerator(rescale = 1./255, rotation_range = 5, width_shift_range = .05, height_shift_range = .05)
  generator = datagen.flow_from_directory(directory = path, target_size = (512,512),color_mode='grayscale', batch_size = 1, class_mode = None, seed = seed)
  return generator

def preprocess_segm(path):
  seed = 1
  datagen = ImageDataGenerator(rescale = 1./255, rotation_range = 5, width_shift_range = .05, height_shift_range = .05)
  generator = datagen.flow_from_directory(directory = path, target_size = (512,512), color_mode='grayscale', batch_size = 1, class_mode = None, seed = seed)
  return generator